fix/error-handling-status
highcharts/node-export-server pull request #577
Opened 2024-09-18 09:46 UTC by jszuminski

We need to throw an appropriate status, depending on whether the issue was caused by the user or by us (the server).

@PaulDalek you were working on the `ExportError.js` so you may know best which parts of code should be worth replacing or if you would like this `statusCode` passing to look a different way so feel free to push any commits if you'd like it to be solved another way.

2024-09-18 11:09 UTC, PaulDalek commented
@jszuminski Looks good! Setting right status code for each of the `ExportError(...)` occurance should resolve the problem.

2024-09-19 10:37 UTC, PaulDalek approved these changes
Good work!

2024-09-20 09:11 UTC, cvasseng requested changes

2024-09-26 08:40 UTC, cvasseng approved these changes

2024-09-26 08:41 UTC, merged